### PR TITLE
Adding message to warn that Update Manager is not installed

### PR DESCRIPTION
**Pull request by balagan73**
Trying to fix this issue: https://github.com/hechoendrupal/DrupalConsole/issues/1824

### CODE REVIEW

**Comment by enzolutions** [comment]
@balagan73 what do you mean by update manager, could you share with us if you get an error?

**Comment by balagan73** [comment]
I have got the error mentioned in the issue [#1824](https://github.com/hechoendrupal/DrupalConsole/issues/1824)

**Comment by enzolutions** [comment]
@balagan73 actuall the code has a validation if is installed

```
if($drupal->isInstalled()) {
```

Looks like in your machine the boot is reporting that drupal is boot and then doesn't load update manager.

**Comment by balagan73** [comment]
I suppose $drupal-isInstalled returns true if Drupal is installed, but does not check if the Update Manager module is installed. this->getSite()->getDrupalVersion() executes the following:
```
        $projects = $this->getDrupalApi()->getService('update.manager')->getProjects();
        return $projects['drupal']['info']['version'];

```
So in order to invoke getService('update.manager') the Update Manager module needs to be installed.

Btw, I was trying to dig down, how this $drupal object is built up. I saw that the HelperSet class of Symfony is responsible for it, but I could not find any instantiation of the AboutCommand class.
I wonder how it is done?

**Comment by jmolivas** [comment]
@balagan73 @enzolutions: I can confirm I was able to replicate this by:
* Uninstalling the Update Manager module
```
drupal module:uninstall update
```

        $systemManager = $this->getSystemManager();
        $requirements = $systemManager->listRequirements();
        $drupalVersion = current(array_filter($requirements, function($v, $k) {
            if ($v['title'] == 'Drupal') {
                return true;
            }
        }));
        $drupalVersion['value'];

**Comment by jmolivas** [comment]
I sent a PR https://github.com/hechoendrupal/DrupalConsole/pull/1837 with the fixes.

**Comment by jmolivas** [comment]
@balagan73: Thanks for the PR. fixed and merged.

**Pull request merged**
