### PR TITLE
[generate:entity:*] Updated entity generator messages to match content and config entities.

### PR DESCRIPTION
**Pull request by rteijeiro**
Not sure if this is the best way but I would be great to distinguish between content and config entities when using generate:entity commands.

### CODE REVIEW

**Comment by jmolivas** [comment]
@rteijeiro: Thanks for the PR. I really like the idea, but a better approach could be to replace the ` if ('EntityContent' == $this->entityType) {` and take advantage of the `$commandName` local property and implementing this code at the `configure` method at `EntityCommand`.

```
    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $commandKey = str_replace(':', '.', $this->commandName);

        $this
            ->setName($this->commandName)
            ->setDescription(
                sprintf(
                    $this->trans('commands.'.$commandKey.'.description'),
                    $this->entityType
                )
            )
            ->setHelp(
                sprintf(
                    $this->trans('commands.'.$commandKey.'.help'),
                    $this->commandName,
                    $this->entityType
                )
            )
            ->addOption('module', null, InputOption::VALUE_REQUIRED, $this->trans('commands.common.options.module'))
            ->addOption(
                'entity-class',
                null,
                InputOption::VALUE_REQUIRED,
                $this->trans('commands.'.$commandKey.'.options.entity-class')
            )
            ->addOption(
                'entity-name',
                null,
                InputOption::VALUE_REQUIRED,
                $this->trans('commands.'.$commandKey.'.options.entity-name')
            )
            ->addOption(
                'label',
                null,
                InputOption::VALUE_REQUIRED,
                $this->trans('commands.'.$commandKey.'.options.label')
            );
    }
```

**Comment by jmolivas** [comment]
@rteijeiro: I will go ahead and send a PR including your changes, this code I shared above and other small improvement for this generator classes.

**Comment by jmolivas** [comment]
I did merged the PR #1323 including changes on your PR.

**Comment by rteijeiro** [comment]
Great! Thanks :+1:

**Pull request merged**
