### PR TITLE
2593 locale namespace

### PR DESCRIPTION
**Pull request by novia713**
i have a lot of weird errors on my machine but this ought works
please, somebody test it and give me feedback
thanks a lot

### CODE REVIEW

**Comment by jmolivas** [comment]
@novia713 thanks for the PR

Could you make the following changes to all of the Commands on this PR

* Add `use` keyword

```
use Drupal\Console\Annotations\DrupalCommand;
```

* Update annotation
```
/**
 * @DrupalCommand(
 *     extension = "locale",
 *     extensionType = "module"
 * )
 */
```

**Comment by novia713** [comment]
the annotation changes were done, sir @jmolivas

**Comment by jmolivas** [comment]
@novia713 do you mind to sync with master again.

**Comment by novia713** [comment]
sync'ed, @jmolivas

**Comment by jmolivas** [comment]
I got this error
>  File not found at "translations://drupal-8.1.8.es.po" nor at "http://ftp.drupal.org/files/translations/8.x/drupal/drupal-8.1.8.es.po"

locale-translation-status-error

Maybe @enzolutions have a abetter idea why is this happening.

**Comment by novia713** [comment]
yes, @jmolivas this is the bug #2637
i'm looking for a solution right now ...

**Pull request merged**
