### PR TITLE
Update composer dependencies

### PR DESCRIPTION
**Pull request by webflo**
This updates all Symfony components, twig and phpunit to the same version we use in Drupal core (8.0.x-dev). https://packagist.org/packages/drupal/core

### CODE REVIEW

**Comment by tarjei** [comment]
Is there anything holding up this PR?

/me just waiting for it :)

**Comment by webflo** [comment]
We have to fix https://github.com/hechoendrupal/DrupalConsole/pull/659 before

**Comment by jmolivas** [comment]
Beta11 still requiring "2.6.*", since we are in sync with latest Beta release maybe make sense to wait until new Drupal releas is tagged.

https://github.com/drupal/drupal/blob/8.0.0-beta11/core/composer.json

**Comment by webflo** [comment]
@jmolivas @omero I think this is good to go. beta12 was released yesterday. Or do you have objections?

**Comment by jmolivas** [comment]
Make sense to merge this now and tag a new release to support latest Beta 12.

I already confirmed `2.7` is the required version for the Beta12 release.
https://github.com/drupal/drupal/blob/8.0.0-beta12/core/composer.json#L9

**Comment by omero** [comment]
Just a little change `drupal/core": "8.0.*@dev` for `drupal/core": "8.0.0-beta12` :P :+1:

**Comment by jmolivas** [comment]
I believe we can remove the `drupal/core` dependency.

**Comment by webflo** [comment]
Done :)

**Comment by jmolivas** [comment]
Thanks for the PR @webflo, I got it merged.  

Thanks for reviewing @omero 

I will tag a new release and I will ping you once is done @tarjei

**Comment by tarjei** [comment]
Thanks!

2015-07-01 15:39 GMT+02:00 Jesus Manuel Olivas <notifications@github.com>:

> Thanks for the PR @webflo <https://github.com/webflo>, I got it merged.
>
> Thanks for reviewing @omero <https://github.com/omero>
>
> I will tag a new release and I will ping you once is done @tarjei
> <https://github.com/tarjei>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hechoendrupal/DrupalConsole/pull/652#issuecomment-117679782>
> .
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Pull request merged**
