### PR TITLE
Fix "Call to undefined function xy()" issue in generate:plugin:field command.  #1885

### PR DESCRIPTION
**Pull request by mxr576**
Same askEmpty() issue as in #2111. Bug report: #1885

### CODE REVIEW

**Comment by jmolivas** [comment]
@mxr576 Thanks for your contribution! We'll take a look at it as soon as possible!

**Comment by jmolivas** [comment]
This makes me think we may need to fix the `askEmpty` method.

**Comment by mxr576** [comment]
At least the documentation of the method, which I've already done in my previous pull request. Someone misused this method multiple times, because he/she did not know that its second parameter should be a callable.

**Comment by jmolivas** [comment]
True because must be the validator.

**Comment by jmolivas** [comment]
@mxr576 PR was merged. This will be included on next release, Thanks.

**Pull request merged**
