### PR TITLE
Add a generator for installation profiles.

### PR DESCRIPTION
**Pull request by pfrenssen**
This is a PR for issue #295.

### CODE REVIEW

**Comment by pfrenssen** [comment]
This is based on the example at the official documentation: https://www.drupal.org/node/2210443. All code has been stolen from the module generator.

It's still in progress, I currently have an issue where Twig cannot find the template:

```
 [Twig_Error_Loader]                                                                                                 
  Unable to find template "profile/info.yml.twig" (looked into: /home/pieter/v/joinup/vendor/drupal/console/src/Command/../../templates).
```

**Comment by pfrenssen** [comment]
Ok so the Twig issue was a bit special. I have DrupalConsole installed globally on my system and always use this global instance. I wasn't aware that the Drupal 8 site I was using to test also had DrupalConsole installed as a composer dependency. Twig was looking for the templates in the local composer managed instance instead of in the global instance I was running. This is maybe a bug, but unrelated to this PR.

I found a few small bugs when I was able to run the code and fixed them.

**Comment by pfrenssen** [comment]
Added a test. I found a violation against proper OO decoupling thanks to the test :)

**Comment by pfrenssen** [comment]
Note that the test is only checking that the files are being generated, it doesn't check the content of the files. This is in line with what the other tests are doing. I can extend the tests to check the contents as well if this is desired.

**Comment by jmolivas** [comment]
@pfrenssen: At this point asking for the generated files is fine. we can decide later on if we want to validate file contents.

**Comment by jmolivas** [comment]
@pfrenssen: Thanks for the  PR.

**Pull request merged**
