### PR TITLE
Fix Travis CI Integration

### LINKED ISSUE #658: Travis CI Integration is broken
All Travis CI builds are marked as successful regardless of errors during build. Example https://travis-ci.org/hechoendrupal/DrupalConsole/jobs/65820861#L166

Related PR: #654

### PR DESCRIPTION
**Pull request by webflo**
Fixes #658

@jmolivas I am not sure about the ``drupal chain`` build step, because the commands throughs an error but the exit code is 0.

### CODE REVIEW

**Comment by jmolivas** [comment]
@webflo The `chain` command allows you to execute multiple commands based on what is defined on a yml file.

The following line si suppose to exit if any error are detected on the drupal coding standards after generating the module using the `chain command`.
```
 if ~/.composer/vendor/bin/phpcs 
--standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml 
modules/custom/example | egrep "FOUND ([1-9]+) ERRORS" --quiet ; then echo 
"Errors in coding standards"; exit 1; else echo "Coding standards check completed"; 
exit 0; fi
```

**Comment by webflo** [comment]
But the previous line in the repo it exactly the same thing without the condition. So its okay to remove it?

**Comment by jmolivas** [comment]
I rather like to remove the previous line and fix this one to make sure exit with 1 when outputted any ERROR.

**Comment by webflo** [comment]
It exists with exit code 1 on my local machine. Don´t know whats wrong on travis.

**Comment by jmolivas** [comment]
@webflo Looking at the `.travis.yml` file I saw we should use Beta11 instead of Beta9

Original
```
- ~/.composer/vendor/bin/drush dl drupal-8.0.0-beta9
- mv drupal-8.0.0-beta9 drupal8.dev
```
Must be
```
- ~/.composer/vendor/bin/drush dl drupal-8.0.0-beta11
- mv drupal-8.0.0-beta11 drupal8.dev
```

**Comment by webflo** [comment]
Added it and incorporated the changes from #660

**Comment by jmolivas** [comment]
I saw a different error, when  trying to download drupal using drush 

```
~/.composer/vendor/bin/drush dl drupal-8.0.0-beta11
simplexml_load_file(): I/O warning : failed to load external entity  [warning]
"" Project.php:72
Failed to get available update data from                             [error]
https://updates.drupal.org/release-history/drupal/8.x
Could not download requested project(s).                             [error]
```

**Comment by webflo** [comment]
I think the drush erorrs are related to https://twitter.com/drupal_infra/status/608307465634123777

**Comment by jmolivas** [comment]
Probably, if the issues is related to that link, then we need to wait until it's fixed o maybe I can do little changes to `console` `module:download` command and add a path to download.

screen shot 2015-06-09 at 4 16 16 pm

**Comment by jmolivas** [comment]
I tried `drush dl drupal-8.0.0-beta11` on my local and works fine 
screen shot 2015-06-09 at 4 21 53 pm

**Comment by webflo** [comment]
@jmolivas The last build looks good, i managed to the the chain command running. I had to subclass ExtensionDiscovery to resolve the issue. Core patch is comming ...

**Comment by webflo** [comment]
Core issue: https://www.drupal.org/node/2503927

**Comment by jmolivas** [comment]
I fixed the errors on the templates files to make this project is Drupal Coding Standards compliant https://github.com/hechoendrupal/DrupalConsole/pull/668

**Comment by jmolivas** [comment]
@webflo may you pass `-n` to mute the warning messages and remove verbose `-v` also please remove the debugging code `echo`, `ls` and `tree` to test the build again.

**Comment by jmolivas** [comment]
@webflo I done the following updates:
* Fixed Drupal coding standards #668 
*  Mark Test Incomplete #671 

And then run the build manually, this is the build URL: 
https://travis-ci.org/hechoendrupal/DrupalConsole/builds/66375735

Let's see if build passes.

**Comment by webflo** [comment]
(PR squashed)

**Comment by jmolivas** [comment]
Yay is green, I think is safe to ahead and merge this PR.

**Comment by omero** [comment]
Awesome work !!! i made some test form this side and looks good to me :+1:

**Comment by jmolivas** [comment]
Thanks for the PR and all your work @webflo 

Thanks for testing this @omero

**Pull request merged**
