### PR TITLE
[generate:entity:content:bundled] - new command for creating custom fieldable content entities with bundle support

### PR DESCRIPTION
**Pull request by frega**
### Problem/Motivation:

This article "How to create custom entities with bundle support in Drupal 8"  http://www.agoradesign.at/blog/how-create-custom-entities-bundle-support-drupal-8 the issue #1139 outlines the background why a distinct command is necessary.

There is quite a lot (and finicky) boilerplate code needed to turn a custom entity into being "with a bundle" like many other core entities (e.g. block_content ...). This includes a controller (as well as a theme function and template), adjustments to the routing.yml, menu.yml and links.yml files as well as changes to the content entity base field definitions and, finally, some adjusted annotations for both config and content entity.

### Solution:
The PR is a initial stab (some ugly hacks and coding standard not adhered too, sorry). But with this approach you can get to a custom fieldable content entity in four steps w/ drupal console. 

It is unclear to me, in how far we should keep separate template-files for the different use-cases, in two cases I 'hacked' templates and in the other cases I replace

### Steps to Reproduce:

1. Create a module:
`console generate:module --module=xxx_test` 
and hit enter a couple of times :)
2. Create a content entity with "bundle support":
`console generate:entity:content:bundled --module xxx_test --entity-class XxxTestEntity`
and hit enter a couple of times :)
3. Manually merge the hook_theme-implementations in xxx_test.module 
4. Enable the module xxx_test, goto http://YOURD8INSTALL/admin/structure/xxx_test_entity_type create a bundle or two (feel free to add a field or two) and then proceed to http://YOURD8INSTALL/admin/xxx_test_entity click add - if you added more than one bundle after choosing the bundle/type - create the content entity.

### CODE REVIEW

**Comment by enzolutions** [comment]
@frega in new PR we don't get how to create bundles, we can do a session via hangout to double check?

**Comment by frega** [comment]
@enzolutions will try to reach out to you later. But here the slightly adjusted steps to reproduce here (i can't seem to get the non-interactive stuff right, sorry :( ...)

1. Create a module: console generate:module --module=xxx_test and hit enter a couple of times :)
2. Create a content entity with "bundle support": generate:entity:content --module xxx_test --entity-class XxxTestEntity and hit enter a couple of times - say *yes* to has-bundle (last question).
3. Very important: merge the hook_theme-implementations in xxx_test.module
4. Enable the module xxx_test, goto the config entity (bundle) admin page: 
http://YOURD8INSTALL/admin/structure/xxx_test_entity_type create a bundle - *important* run: drush cr after creating a new bundle (otherwise core does not seem to pickup on the new bundle).
5. Goto the content entity admin page: http://YOURD8INSTALL/admin/xxx_test_entity add some content.

**Comment by heddn** [comment]
Cross-linking: https://github.com/Jaesin/content_entity_base/issues/6

**Comment by enzolutions** [comment]
Thanks @frega I will work to apply fixes for pending issues

**Comment by heddn** [comment]
Hopefully, with time https://github.com/Jaesin/content_entity_base/issues/6 will also land. Either in core or in contrib land. That should make this 10x easier.

**Pull request merged**
