### PR TITLE
Fix wrong variable name

### LINKED ISSUE #2776: [config:export:single] PHP Fatal error:  Call to a member function getStorage()
```
drupal config:export:single -c 
 Configuration type [Simple configuration]:
 > some_config
PHP Fatal error:  Call to a member function getStorage() on null in /var/www/html/drupal8/vendor/drupal/console/src/Command/Config/ExportSingleCommand.php on line 127
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/drupal:3
PHP   4. Drupal\Console\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:64
PHP   5. include_once() phar:///usr/local/bin/drupal/src/Utils/Launcher.php:32
PHP   6. Symfony\Component\Console\Application->run() /var/www/html/drupal8/vendor/drupal/console/bin/drupal.php:50
PHP   7. Drupal\Console\Application->doRun() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:123
PHP   8. Drupal\Console\ConsoleApplication->doRun() /var/www/html/drupal8/vendor/drupal/console/src/Application.php:39
PHP   9. Symfony\Component\Console\Application->doRun() /var/www/html/drupal8/vendor/drupal/console-core/src/ConsoleApplication.php:88
PHP  10. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:192
PHP  11. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:863
PHP  12. Drupal\Console\Command\Config\ExportSingleCommand->interact() phar:///usr/local/bin/drupal/vendor/symfony/console/Command/Command.php:244
PHP  13. Drupal\Console\Command\Config\ExportSingleCommand->getConfigNames() /var/www/html/drupal8/vendor/drupal/console/src/Command/Config/ExportSingleCommand.php:174

```

### PR DESCRIPTION
**Pull request by dosten**
This PR fixes #2776

### CODE REVIEW

**Comment by dosten** [comment]
@jmolivas as @igasi says, this PR fixes the issue, do you need something else to merge this one?

**Comment by jmolivas** [comment]
@dosten testing it, I will test in a couple of hours.

Thanks for the PR @dosten and @igasi for testing it.

**Comment by dosten** [comment]
ping @jmolivas

**Comment by jmolivas** [comment]
@dosten Thanks for your contribution, your PR was merged. This will be included on the next release.

**Pull request merged**
