### PR TITLE
[generate:entity:*] #1392: enrich both entity interface and model, add support for status…

### PR DESCRIPTION
**Pull request by smalot**
… (published / unpublished), change security logic

### CODE REVIEW

**Comment by jmolivas** [comment]
@smalot: May you fix the conflicts to merge this PR?

**Comment by smalot** [comment]
Done   ;-)

**Comment by jmolivas** [comment]
thanks, Will review and merge this and include on the next release v0.9.11, tagged  probably during this week

**Comment by smalot** [comment]
Thanks

**Comment by jmolivas** [comment]
@smalot: Thanks for the PR and fixes.

**Comment by smalot** [comment]
You are welcome. 
Thanks

**Pull request merged**
