### PR TITLE
[help] Make command translatable and a little zh_hans translation update.

### PR DESCRIPTION
**Pull request by ranqiangjun**
I create an issue [here](https://github.com/hechoendrupal/DrupalConsole/issues/1790) ( [Translation] Make help command translatable #1790). 

Please review this PR, Thanks!

### CODE REVIEW

**Comment by jmolivas** [comment]
@ranqiangjun: Thanks for the PR :+1: on this feature.
I tested and found a different output when running the drupal --help
* Original:
drupal-help-original

* Updated:
drupal-help-updated

**Comment by ranqiangjun** [comment]
I noticed that. But I don't know how to fix it right now. I'll try to fix it later. Any suggestions on how to fix it?  Thanks!

**Comment by ranqiangjun** [comment]
Fixed @jmolivas Thanks!
fixed

**Comment by ranqiangjun** [comment]
@enzolutions Conflicts resolved, Thanks!

**Comment by enzolutions** [comment]
testing

**Comment by jmolivas** [comment]
Looks great.

**Pull request merged**
