### PR TITLE
968 - Remove conflicting configuration files from generator.

### PR DESCRIPTION
**Pull request by VasquezPonte**
#968

### CODE REVIEW

**Comment by jmolivas** [comment]
@VasquezPonte I do like the idea, I will test it and ping you.

**Comment by VasquezPonte** [comment]
Thanks @jmolivas . Let me know if you have any questions or if I can help expedite the review process.

**Comment by jmolivas** [comment]
@VasquezPonte: Since those two files are no longer generated we may need to deleted these twig files: 
- `module/src/Entity/Bundle/core.entity_view_mode.node.teaser.yml.twig`
- `module/src/Entity/Bundle/field.storage.node.body.yml.twig`

**Comment by VasquezPonte** [comment]
Thanks to @jmolivas  for the hint. Files are now deleted.

**Comment by jmolivas** [comment]
@VasquezPonte: Thanks for the PR.

**Pull request merged**
