### PR TITLE
#663 Generated entity links should point to paths, not routes

### PR DESCRIPTION
**Pull request by heilop**
I changed point to paths.

### CODE REVIEW

**Comment by webflo** [comment]
@heilop Prefix ``/node`` is wrong. Please use the same url patterns as in https://github.com/hechoendrupal/DrupalConsole/blob/master/templates/module/routing-entity-content.yml.twig

**Comment by heilop** [comment]
Thanks @webflo, I will change that.

**Comment by jmolivas** [comment]
Thanks for the PR @heilop

**Comment by heilop** [comment]
Thanks for help me @jmolivas 
Thanks @webflo for the code review 
yay!!

**Pull request merged**
