### PR TITLE
#649 fixed ruleaction command

### PR DESCRIPTION
**Pull request by sajalsoni**
@jmolivas 

Can you please check this PR?

Thanks,
Sajal

### CODE REVIEW

**Comment by jmolivas** [comment]
Thanks for the PR @sajalsoni looks great, I tested and have a few notes:

- The `cache` is no longer and option now is an argument and must be passed without `--`
```
# Actual code on the PR:
$this->getHelper('chain')->addCommand('cache:rebuild', ['--cache' => 'discovery']);

# Must look like:
$this->getHelper('chain')->addCommand('cache:rebuild', ['cache' => 'discovery']);
```

- The `system.action.default_action.yml` file must en with a new empty line.

- When testing the drupal conding standards of the generated code and this is the output:
```
~/.composer/vendor/bin/phpcs --standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml modules/custom/example

FILE: ...8.dev/modules/custom/example/src/Plugin/Action/DefaultAction.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 29 | ERROR | [x] Whitespace found at end of line
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

This can be fixed by removing the two spaces at line 34 of the twig template `modules/custom/example/src/Plugin/Action/DefaultAction.php`

**Comment by sajalsoni** [comment]
Hi @jmolivas,

Ok fixed those changes, and updated the PR.

I have a query here. I'm not sure if I've followed the correct way to update the PR. Since, I had to merge the upstream changes to my local master branch to remove that '--cache' issue. So the commit history was something like,

- My latest fix (#649 fixes suggested by jmolivas)
- Changes I pulled from Upstream since my last update
- My earlier fixes (#649 fixed ruleaction command)

Is that fine Or could I followed better workflow to keep my all commits in proper order?

Thanks,
Sajal

**Comment by jmolivas** [comment]
@sajalsoni I just updated the documentation pages, related to the question you just did:

* [Contributing new features](http://hechoendrupal.gitbooks.io/drupal-console/content/contributing/new-features.html)
* [Keeping your fork up to date](http://hechoendrupal.gitbooks.io/drupal-console/content/contributing/keeping-your-fork-up-to-date.html)

**Comment by jmolivas** [comment]
I tested this and the issues got fixed.

Thanks for the PR @sajalsoni

**Comment by sajalsoni** [comment]
@jmolivas,

Thanks for the document links. I think understand it now, I should create a new feature/bugfix branch locally, and should do all the work in that, so that master branch can be synced from the upstream easily. 

Also, I should push that feature/bugfix branch to github, so that I can initiate the PR from that branch itself instead of master branch. Once issue is solved, we should merge that topic branch to master. And finally, moderator will merge the upstream by fetching changes from my master branch.

**Pull request merged**
