### PR TITLE
[module:uninstall] added a force option to the module uninstall comma…

### LINKED ISSUE #1745: [module:uninstall] add force uninstall option
## Motivation
During intensive development we sometimes need to re-install modules that are dependent upon by other modules.

## Solution
Adding  an option to the module uninstall command to ignore dependencies

### PR DESCRIPTION
**Pull request by Eyal-Shalev**
…nd that ignores dependencies, fix #1745.

### CODE REVIEW

**Comment by jmolivas** [comment]
@Eyal-Shalev: PR is no longer in sync with master, do ypu mind to sync with latest changes.

**Comment by jmolivas** [comment]
@Eyal-Shalev: We already had a global `--yes` option we have been using to bypass some confirmation questions. 

We can probably reuse that instead of the new `--force` any thoughts ? cc: @enzolutions @omero

**Comment by enzolutions** [comment]
I prefer the global opton than include a --force option

**Comment by darol100** [comment]
I think they are different, `--yes` is different from `--force` correct me if I'm wrong @Eyal-Shalev . `--yes`, will add the ability to said yes to everything meaning that if you trying to uninstall a module with dependency is going to uninstall their dependency. Compare to the `--force` it will allow you to remove it the ability remove it without removing the dependency.

**This comment is all base on theory, I have not try it out the** `--yes` **and/or** `--force`.

**Comment by Eyal-Shalev** [comment]
@darol100 you are correct.

The --force option should uninstall a module and leave the dependencies installed.

We could also add a --yes option that will uninstall the dependencies.

**Comment by Eyal-Shalev** [comment]
@jmolivas I've updated my fork with the current remote master branch

**Comment by darol100** [comment]
@Eyal-Shalev , There still some problems with CLI. Can you try it to fixed it before a review of this PR ?

**Comment by jenswegar** [comment]
would this also force remove any entities in the storage that are blocking an uninstall?

**Comment by Eyal-Shalev** [comment]
It's been a while since I worked on it.
But if I remember correctly then you will not be able to uninstall if there
is content that depends on this module.

On Thu, Mar 17, 2016, 12:08 Jens Wegar <notifications@github.com> wrote:

> would this also force remove any entities in the storage that are blocking
> an uninstall?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hechoendrupal/DrupalConsole/pull/1746#issuecomment-197801287>
>
-- 

Regards,
Eyal Shalev

**Comment by darol100** [comment]
I did not how to contribute to that PR. So I reroll this PR into another branch. And I fixed the issue with Travis and the merge conflicts at https://github.com/hechoendrupal/DrupalConsole/pull/2073.

I did it base on @Eyal-Shalev branch so it contains his commit (work), which I do not want to take credit it for it.

I'm going to close this PR so we can continue it at https://github.com/hechoendrupal/DrupalConsole/pull/2073.

**Pull request closed without merging**
