### PR TITLE
Listing entity field info - code adapted from http://dgo.to/field_report module

### PR DESCRIPTION
**Pull request by stevepurkiss**
Creating new PR for #1863 after git knowledge fail;) Will close old one.

### CODE REVIEW

**Comment by stevepurkiss** [comment]
So... you can now restrict `field:info` to a specific entity type, for example:

`drupal field:info --entity-type=node`

If you select one which doesn't exist, e.g. `nodes` it will display an error message. This doesn't cope for if you select a non-fieldable entity type, not sure how necessary it is to cope for that - I guess I could say entity type found but not fieldable, am parking that one for the moment as it's tea-time @purkisshq!

field-info-entity-type

The code is still very if...else etc. rather than funky functions but hey, I'm old & can always refactor :D

**Comment by stevepurkiss** [comment]
...or I could just change the error message to say 'Fieldable entity type X not found'... let me know your thoughts.

**Comment by stevepurkiss** [comment]
Actually I might just do it ;) brb...

**Comment by stevepurkiss** [comment]
There we go.

field-info-entity-type-not-found

**Comment by stevepurkiss** [comment]
Just improving my error checking code, didn't actually check whether a specific entity type was selected when checking whether it was found or not. It would only error if there were no fieldable entities anyway, but, y'know... ;)

**Comment by stevepurkiss** [comment]
OK, I think this is ready for review! You can:

- select `--detailed` output which displays descriptions and machine names of entities and bundles
- select `--entity=[ENTITY]` to restrict to a specific entity type e.g. `--entity=node` (shortened but can revert to `--entity-type` if that's 'better')
- select `--bundle=[BUNDLE]` to restrict to a specific bundle type e.g. `--bundle=article` (shortened but can revert to `--bundle-type` if that's 'better')

field-info-entity-bundle

**Comment by stevepurkiss** [comment]
Just added a counter so if there's no fields it displays an appropriate message, and made the current messages re no fields a bit more descriptive. Still ready to test, now looking into how I can make the code more 'current' than procedural ;) Still works though...

**Comment by stevepurkiss** [comment]
Hmm... think I'm gonna leave the code as it is for the moment - there's little I can see that'll improve the computational speed by splitting up the execute function. I'm open to suggestions as realise my mind mostly sees procedural code & would like to improve that ;)

The main reason for lots of code is the ability to get a list of fieldable entities from Drupal (as opposed to a list of just fieldable node types), most of that code is from the source module http://dgo.to/field_report.

I've looked through the latest Drupal API & found [EntityTypeBundleInfoInterface](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21EntityTypeBundleInfoInterface.php/interface/EntityTypeBundleInfoInterface/8.2.x) & tried to get it working yesterday but without luck - if this is a Good Way Forward then let me know your thoughts & will pursue that line, in the mean time I'm gonna have a break as think this is Good Enough for a 1st version of `field:info` command!

**Comment by stevepurkiss** [comment]
Just fixing a standards issue, forgot to run phpcs ;)

**Comment by stevepurkiss** [comment]
FYI am going through sorting out dependency injection etc., squashing & pushing as I get to incremental working stages so code *should* improve ;)

**Comment by stevepurkiss** [comment]
OK, I have to focus on other stuff for a bit so leaving as-is for now, welcome any input/feedback on the code so far - have tidied up design a bit too so it's using $io->comment instead of $io->commentBlock which is a bit 'in yer face' for the actual messages output.

Hope this is ok - functionality will hopefully be useful to ppl!

**Comment by stevepurkiss** [comment]
OK ignore my last comment - just noticed a big chunk of code from the original module which was not really necessary - renaming the entity / bundleParent labels, so just using the labels.

**Comment by stevepurkiss** [comment]
OK, seems EntityTypeBundleInfoInterface functionality is available from the entity type manager but doesn't seem to help reduce the amount of functionality needed to get the list of fieldable entities so leaving that as is.

Will improve code if I figure anything else out, apart from that it's gonna sit here waiting review - everyone's busy on rc1 at the moment so looking forward to seeing that get released yay!

**Comment by stevepurkiss** [comment]
OK, here's an updated screengrab showing a few options and a couple of errors.

You can now:

- select `--detailed` output which displays descriptions and machine names of entities and bundles
- select `--entity=[ENTITY]` to restrict to a specific entity type e.g. `--entity=node` (shortened but can revert to `--entity-type` if that's 'better')
- select `--bundle=[BUNDLE]` to restrict to a specific bundle type e.g. `--bundle=article` (shortened but can revert to `--bundle-type` if that's 'better')

field-info-output

**Comment by jmolivas** [comment]
@stevepurkiss looks good to me.

**Comment by jmolivas** [comment]
I will merge it and migrate to new command structure.

**Pull request merged**
