### PR TITLE
Postgres support for database commands

### PR DESCRIPTION
**Pull request by ericpugh**
Added ability for sites using 'pgsql' driver to use the "database" commands. Successfully tested all "database" commands with Postgres 9.4. Restore command works on an existing DB, but throws an error if db tables don't already exist. This seems to be a general issue with Drupal 8 support for Postgres and the different method (compared to MySQL) Postgres dumps a database.

### CODE REVIEW

**Comment by darol100** [comment]
@ericpugh , This is relate to #1559 ?

**Comment by ericpugh** [comment]
@darol100 Yes, Postgres only.

**Comment by jmolivas** [comment]
:+1: on this PR.

**Comment by jmolivas** [comment]
@ericpugh: Thanks for the PR.

**Pull request merged**
