### PR TITLE
Fix select field issue in generate:form:config command. Fix: #2111

### PR DESCRIPTION
**Pull request by mxr576**
See: #2111

### CODE REVIEW

**Comment by jmolivas** [comment]
@mxr576: Thanks for the PR.  I tested with Drupal 8.0.x and it works properly.

Did you test with  Drupal 8.1.x?

**Comment by mxr576** [comment]
@jmolivas Yes I did, because the bug report was referred to the 8.1.x.

**Comment by jmolivas** [comment]
@mxr576 I tested as well and it works fine on 8.1.x.

**Comment by jmolivas** [comment]
@mxr576 PR was merged. This will be included on next release, Thanks.

**Pull request merged**
