### PR TITLE
Add Exec command

### PR DESCRIPTION
**Pull request by Saphyel**
### Implementation of #1907  part 1

This command execute an external command, the idea is provide **similar** functionality to `phing`

#### Example of usage:
`drupal exec "ls -al"`

### CODE REVIEW

**Comment by Saphyel** [comment]
@enzolutions  recommended follow [this approach](http://enzolutions.com/articles/2015/11/27/how-to-execute-an-external-php-application-inside-symfonydrupal-in-a-sandbox/)

**Comment by novia713** [comment]
@Saphyel i see you're using _Symfony\Component\Process\Process_;
perhaps you ought use the already existent _/src/Utils/ShellProcess.php_

it in fact also uses _Process()_ but it also shows a percent advance graphic ....
i'm not sure, perhaps _ShellProcess_ is not ideal for you, but i thinked you should know it ....

**Comment by novia713** [comment]
i was being thinking about this.
i suggest you @Saphyel  to use the existing ShellProcess, to avoid duplication
perhaps you should refactor or add more options (to not show the progress bar) to ShellProcess
i did that, ping me anytime if you want talk about this

**Comment by Saphyel** [comment]
I'll try to do it later today, I really appreciate your comments! ^^ I'm learning more than I thought with this PR!

**Comment by Saphyel** [comment]
@novia713 take a look now! :dancer:

**Comment by Saphyel** [comment]
I fixed the output of composer by the way:
screenshot_20160625_143712

**Comment by novia713** [comment]
yes, i was aware of that lack of linebreak in between the progress bar & the info message.
i lived very sad these late days because of it, now i'm happy !! :dancers:

**Comment by novia713** [comment]
reminder for @novia713 (myself) to open an issue to change «shellexec_output» key name in config.yml in favour of «composer_output» when this PR were merged

**Comment by jmolivas** [comment]
@Saphyel PR was merged. This will be included on next release, Thanks.

@novia713 Thanks for helping to test and commenting.

**Pull request merged**
