### PR TITLE
[translation] french - misc and create.*

### PR DESCRIPTION
**Pull request by kgaut**
Some typo, syntax error and new french translations.

Translation of all strings used on "welcome" screen.

Also correct a glitch we have because of a syntax error.

### CODE REVIEW

**Comment by enzolutions** [comment]
@kgaut I apply some fixedin french and other languages.

Could you sync and merge with master as you can see in guide https://hechoendrupal.gitbooks.io/drupal-console/content/en/contributing/keeping-your-fork-up-to-date.html then merge and resolve any conflicts

let me know in gitter if you have any blocker

**Comment by kgaut** [comment]
Ok,  Will do this morning.

**Comment by kgaut** [comment]
Should be ok now.

**Comment by enzolutions** [comment]
Thanks @kgaut

**Pull request merged**
