### PR TITLE
Improved instructions at method title prompt

### PR DESCRIPTION
**Pull request by wranvaud**
as documented on issue https://github.com/hechoendrupal/DrupalConsole/issues/2025

### CODE REVIEW

**Comment by enzolutions** [comment]
Hi @wranvaud Thanks for your contribution.

But you can do an extra work, of replacing the string in all other languages.

You can do this with Drupal Console YAML commands in DrupalConsole language folder **config/translations**

In each language folder, you can run this 

```
$ drupal yaml:update:value ./generate.controller.yml questions.title "Enter the Controller method title (to stop adding more methods, leave this empty)"
```

and

```
drupal yaml:update:value ./generate.controller.yml messages.title-empty "Title must contain a value (you must enter at least one method)"
```

After apply in all language commit the new changes and PR will be updated.

**Comment by enzolutions** [comment]
Thanks @wranvaud for the change, but we don't allow partial lines translated, because the tool we use to report pending translation don't understand that 'yet'. please put the whole line in English.

**Comment by enzolutions** [comment]
@wranvaud  Actually Catalan, Hindi, Indonesian, Vietanesse  and  Chinese Simplified still incorrect, please double check

**Comment by enzolutions** [comment]
Perfect. I am going to merge, thanks for your commitment with this PR @wranvaud , welcome as contributor to Drupal Console project.

**Comment by wranvaud** [comment]
Thank you for your guidance @enzolutions !

**Pull request merged**
