### PR TITLE
Add twig:compile command

### PR DESCRIPTION
**Pull request by mglaman**
Adds a twig:compile command as mentioned in issue #1525. Loads the registry for configured default and admin theme, then processes the theme hook through the theme manager service.

### CODE REVIEW

**Comment by jmolivas** [comment]
@mglaman: Thanks for the PR looks like a useful command. 

I tested and found some issues:

 * Missing class import:  
   `use Drupal\Core\StreamWrapper\PublicStream;` 

* Error when executing on fresh 8.0.2 installation:

> PHP Fatal error:  Call to a member function getCommentedEntity() on a non-object in /Users/jmolivas/develop/drupal/sites/drupal8.dev/core/modules/comment/comment.module on line 623
Fatal error: Call to a member function getCommentedEntity() on a non-object in /Users/jmolivas/develop/drupal/sites/drupal8.dev/core/modules/comment/comment.module on line 623

**Comment by mglaman** [comment]
Bah, I'm not sure how we can work around

````
Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead.
````

**Comment by jmolivas** [comment]
@mglaman: Do you have `pathauto` module installed?

**Comment by mglaman** [comment]
@jmolivas no, vanilla 8.0.x

**Comment by darol100** [comment]
There seem to be some improvement in Drupal Console (https://github.com/hechoendrupal/DrupalConsole/issues/1987). And I do not longer see this error. `Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead.`

However, it seems unclear to me how to test this PR ? @mglaman Can you provide the steps on how to test this PR?

- I delete all my twig compiles`rm -rf sites/default/files/php/twig/`
- Run twig:compile

And did not rebuild all templates. 

What I'm doing wrong ?

**Pull request closed without merging**
