### PR TITLE
[console] Add database dump command

### PR DESCRIPTION
**Pull request by davidDuymelinck**
As promised i've added the beta 12 database dump command to drupal console.

### CODE REVIEW

**Comment by darol100** [comment]
@davidDuymelinck, this seem like a very nice feature to have. For some reason it fails the automate test.

Can you try to re-roll your PR ? This will be something that will be very nice to have.

**Comment by jmolivas** [comment]
@darol100 & @davidDuymelinck we added `database:dump` command, at this point only supports `mysql` because we used `mysqldump` command instead of iterating Database tables.

Command class link https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/Database/DumpCommand.php

**Comment by darol100** [comment]
@jmolivas I'm going to open another stories to handle other types of databases.

**Comment by darol100** [comment]
Support for other database see more at #1559

**Pull request closed without merging**
