### PR TITLE
2593 module namespace

### PR DESCRIPTION
**Pull request by novia713**
`module:install` with injection of dependencies working

just touched the code also for when using `--composer` option it checks wether if we are in "web" or "docroot" and then execute `composer` from an upper directory

i bet without `--composer` option it works well, with this option the only problem i see is when the module wasn't downloaded with composer the `exec` method of `shellprocess` should stop the run

now it looks like this
seleccion_460

anyway, i guess the `--composer` option will be removed, so this is not very important ...

### CODE REVIEW

**Comment by novia713** [comment]
this PR comes from #2593

**Comment by novia713** [comment]
`module:uninstall` reconverted is working

anyway, `module:install` is giving me the following error, any advice?
```
../vendor/bin/drupal module:install devel
PHP Fatal error:  Call to undefined method Drupal\Console\Application::getValidator() in /home/leandro/public_html/hq/vendor/drupal/console/src/Command/Shared/ProjectDownloadTrait.php on line 84
```

**Comment by jmolivas** [comment]
@novia713 there is a valiator service
```
  console.validator:
    class: Drupal\Console\Utils\Validator
```

**Comment by novia713** [comment]
done work in PathCommand & UpdateCommand @jmolivas 

don't kwon why is erroring at inyecting @console.shell_process
this still needs a bit of work extra

**Comment by jmolivas** [comment]
Not sure if `--composer` will stay or go we should talk about this

**Pull request closed without merging**
