### PR TITLE
Issue #2086: Improve installation instructions.

### PR DESCRIPTION
**Pull request by serundeputy**
This fixes: https://github.com/hechoendrupal/DrupalConsole/issues/2086

### CODE REVIEW

**Comment by darol100** [comment]
@jmolivas , Can we just remove README.txt ? Here is a great example why having two files is duplicate of work.

**Comment by darol100** [comment]
@serundeputy , Can you remove the README.txt as part of this PR as well ?

**Comment by serundeputy** [comment]
@darol100 yes; will do.

**Comment by darol100** [comment]
@serundeputy Thanks.

**Comment by dabito** [comment]
@serundeputy It would be great to add a link to the new title "Running Drupal Console" to the top of the file with the rest of the links:

`  - [Running Drupal Console](#running-drupal-console)  
`

**Comment by serundeputy** [comment]
@dabito will do.

**Comment by serundeputy** [comment]
@dabito updated `PR` added link; rebased.

**Comment by dabito** [comment]
Nice! Offtopic: something wrong with ci? It failed for me too only for changing the readme

**Comment by jmolivas** [comment]
@serundeputy : PR was merged. This will be included on next release, Thanks.

**Pull request merged**
