### PR TITLE
update base class, refactor debug and poll commands

### PR DESCRIPTION
**Pull request by twhiston**
Updated version of the database poll command. 

Originally in this PR https://github.com/hechoendrupal/DrupalConsole/pull/2529 but i ended up deleting my branch and refactoring everything, so it also needs a new PR because the old one was auto closed :S

- Added database:log:poll command to poll the db for new log messages every 'x' seconds
- Refactored database:log:debug to share a base class with database:log:poll
- Added option to print single database entry as yml or table format

see https://github.com/hechoendrupal/drupal-console-en/pull/51 for strings

### CODE REVIEW

**Comment by jmolivas** [comment]
@twhiston Thanks for your contribution, your PR was merged. This will be included on the next release.

**Comment by twhiston** [comment]
@jmolivas may i ask why this command isnt in the current rc14 release when it was previously shown as merged? I'd love to get this command into drupal console so please let me know what I can do. Thanks

**Comment by jmolivas** [comment]
@twhiston do mean the `database:log:poll`?

**Comment by jmolivas** [comment]
@twhiston Found the issue and send a PR https://github.com/hechoendrupal/drupal-console/pull/3106  to have it fixed 

The command was not registered as service and therefore not loaded on the application.

**Comment by twhiston** [comment]
Thanks for finding the issue (and fixing it!). Very much appreciated

**Pull request merged**
