### PR TITLE
[container:parameters] Issue #2766: add a container:parameters command.

### PR DESCRIPTION
**Pull request by FGM**
Suggested content for console-en / translations / container.parameters.yml:

description: 'Displays current parameters for an application. Internal parameters of Drupal, Console, and the container are excluded for readability.'

### CODE REVIEW

**Comment by jmolivas** [comment]
@FGM Thanks for your contribution, your PR was merged. This will be included on the next release.

**Comment by FGM** [comment]
Thanks for including it.

**Comment by jmolivas** [comment]
@FGM I like the command but not sure about the name yet.

Maybe `container:debug:parameters` is a better option or do what symfony does add this feature to the `container:debug` command and use it as `container:debug --parameters`

**Comment by FGM** [comment]
Yes, I wondered how to name it too: it should basically just be a part of container:debug, but I did not want to modify this existing well-known command. I hadn't though of the parameters idea: might be the best choice.

**Comment by jmolivas** [comment]
@FGM I moved the code to `drupal container:debug --parameters`

**Comment by jmolivas** [comment]
This is the PR https://github.com/hechoendrupal/DrupalConsole/pull/2826 containing the code relocation.

**Pull request merged**
