### PR TITLE
[self-update] Remove abandonded dependency fix #806

### LINKED ISSUE #806: Abandoned dependency? -- herrera-io/phar-update
It appears the dependency `"herrera-io/phar-update": "1.*"` is abandoned upstream per its' source GitHub owner?: https://github.com/kherge-abandoned/php-phar-update

Are there any plans to replace this dependency with a non-abandoned alternative?  I ask because I would like to eventually package this project downstream for Fedora/EPEL but I do not want to be responsible for packaging an abandoned dependency.

### PR DESCRIPTION
**Pull request by omero**
Replace abandoned dependency `herrera-io/phar-update` with `padraic/phar-updater` this fix #806

### CODE REVIEW

**Comment by jmolivas** [comment]
This fixes #806

**Comment by pjcdawkins** [comment]
As far as I can tell, this means that you no longer verify the SHA1 hash of the downloaded file. For the Platform.sh CLI I'm writing a custom 'strategy' for this library, which uses the old (herrera-io) style "manifest.json" to contain the versions and SHA1 hashes:
https://github.com/pjcdawkins/platformsh-cli/blob/replace-phar-update/src/SelfUpdate/ManifestStrategy.php

**Comment by jmolivas** [comment]
@pjcdawkins Yes we skip the validation and planned to write it later, but we can probably re-use what you did ?

Any reason why you wrote a custom 'strategy' instead of using the one provided by the library https://github.com/padraic/phar-updater#basic-sha-1-strategy ?

**Comment by pjcdawkins** [comment]
The one provided by the library requires you to have the SHA1 in a file on its own at URL - it can't look through a list of versions. Also I included a little bit of logic for the "Lock to major version" option that herrera-io/phar-update had (I've named it as a parameter `$allowMajor`, which you'd set true to allow updates between major versions).

**Pull request merged**
