### PR TITLE
Use drupal finder

### PR DESCRIPTION
**Pull request by jmolivas**

### CODE REVIEW

**Comment by cweagans** [comment]
I think this needs a corresponding `composer.json` update, no?

**Comment by jmolivas** [comment]
@cweagans the `drupal-finder` dependency is at `console-core` https://github.com/hechoendrupal/drupal-console-core/blob/master/composer.json#L54

**Comment by cweagans** [comment]
Oh, I see. We just had an issue where console somehow got installed without drupal-finder.

**Comment by jmolivas** [comment]
@cweagans try executing

```
composer update drupal/console --with-dependencies
```

**Comment by jmolivas** [comment]
@cweagans  We are going to lock console-core and console-en dependencies to DC release version
https://github.com/hechoendrupal/DrupalConsole/issues/3015

We had an issue for that https://github.com/hechoendrupal/DrupalConsole/issues/3015

**Pull request merged**
