### PR TITLE
issue #2131 Removed config.factory service extra 

### PR DESCRIPTION
**Pull request by igasi**
Removed config.factory service extra in generate:form command

### CODE REVIEW

**Comment by jmolivas** [comment]
@igasi nice catch, Thanks for your contribution! We'll take a look at it as soon as possible!

**Comment by igasi** [comment]
Thx.

**Comment by jmolivas** [comment]
@igasi PR was merged. This will be included on next release, Thanks.

**Comment by igasi** [comment]
Thx.

**Pull request merged**
