### PR TITLE
Add composer.json to ModuleGenerator

### PR DESCRIPTION
**Pull request by sethfischer**
Create composer.json in the module root.

### CODE REVIEW

**Comment by jmolivas** [comment]
Thats for the PR @sethfischer, I like the idea, how about adding an argument and interactive question on the module generator class to generate only if user pass `--composer` inline or answer yes to something like `Do you want to add a composer.json file to your module ?`

**Comment by sethfischer** [comment]
Great idea @jmolivas. I'll update the PR.

**Comment by jmolivas** [comment]
@sethfischer: Feel free to ask any question commenting in this thread or using the project chat https://gitter.im/hechoendrupal/DrupalConsole

**Comment by sethfischer** [comment]
@jmolivas: I've updated this PR so that composer.json is only generated if the option `--composer` is specified, or the user responds yes to the interactive question "Do you want to add a composer.json
file to your module?". I welcome your comments on my implementation.

**Comment by jmolivas** [comment]
Looks fine to me

**Comment by jmolivas** [comment]
Thanks for the PR @sethfischer

**Pull request merged**
