### PR TITLE
[cache:context:debug] Create command and move cache:rebuild command 

### PR DESCRIPTION
**Pull request by smalot**
Create cache:context:list command and move cache:rebuild command into new namespace.

### CODE REVIEW

**Comment by smalot** [comment]
This new command list all available contexts which can be used in cache config:
https://www.drupal.org/developing/api/8/cache/contexts

Useful if context are added via multiple contrib modules

**Comment by enzolutions** [comment]
Awesome contribution @smalot , only a small change, please rename the class and debug as **cache:context:debug** to maintain consistency with others commands

**Comment by smalot** [comment]
Ok for me, with great pleasure !

**Comment by jmolivas** [comment]
@smalot Do you mind to:

1) Rename commands classes

`src/Command/Cache/CacheRebuildCommand.php`
as 
`src/Command/Cache/Cache/RebuildCommand.php`

`src/Command/Cache/CacheContextListCommand.php`
as
`src/Command/Cache/ContextDebugCommand.php`

2) Update `config/services/cache.yml` file to reflect namespace changes.

3) Update command classes

`use Symfony\Component\Console\Command\Command as BaseCommand;`
and
`class CacheContextListCommand extends BaseCommand`

with 

`use Symfony\Component\Console\Command\Command;`
and
`class CacheContextListCommand extends Command`

**Comment by enzolutions** [comment]
Works like a charm, thanks @smalot

**Comment by smalot** [comment]
My pleasure !

**Comment by jmolivas** [comment]
@smalot great work, thanks for the PR and the super-fast reply.

**Pull request merged**
