### PR TITLE
Set config entity path to admin/system/[entity name]

### PR DESCRIPTION
**Pull request by Sutharsan**
This makes the config entity path consistent. See  https://github.com/hechoendrupal/DrupalConsole/issues/722

### CODE REVIEW

**Comment by Sutharsan** [comment]
I don't see how this Travis error is related to the included change.

**Comment by jmolivas** [comment]
@Sutharsan: I restarted few times already but keep failing, I will test the code locally and add the results as comments.

**Comment by jmolivas** [comment]
I did run it again and now it's green.

**Comment by jmolivas** [comment]
@Sutharsan: Thanks for the PR

**Pull request merged**
