### PR TITLE
working disable cache page in site:mode dev

### PR DESCRIPTION
**Pull request by novia713**
this comes from https://github.com/hechoendrupal/DrupalConsole/pull/2969

it's a fresh and actulized PR for easy merge 😉

### CODE REVIEW

**Comment by novia713** [comment]
##CAUTION: 

i added to my composer.json of `drupalconsole` this package →
https://packagist.org/packages/novia713/maginot
this is mandatory to work

strangely, it didn't work with the actual `drupalconsole` code, so i had to do a 
`composer require novia713/maginot` 
on my drupal directory.

--

##WHAT THIS PR DOES

`site:mode dev` →
adds  
```php
<?php include __DIR__ . "/settings.local.php"; ?>
```
to `settings.php` and comments out the `cache bins` lines in `settings.local.php`

`site:mode prod` →
removes the include to `settings.local.php` in `settings.php`

that's all!  🎆

**Comment by FatherShawn** [comment]
But what if the user wants to check site function in mode prod locally?  We have our local db creds and so forth in `settings.local.php`

**Comment by novia713** [comment]
@FatherShawn hmmm maybe i'm wrong, but AFAIK the `settings.local.php` should not have the credentials for the dev site

here it is the description of the `settings.local.php` file in the `settings.php`
> Typically used to disable
>  * caching, JavaScript/CSS compression, re-routing of outgoing emails, and
>  * other things that should not happen on development and testing sites.

**Comment by FatherShawn** [comment]
We use it for credentials to the local developer's site, not a server.  And it's common for our devs to switch site mode on and off locally, so `site:mode` is used in local dev for us.

**Comment by novia713** [comment]
@FatherShawn so, if i understand well, you have the `include 'settings.local.php'` at the end of the `settings.php`, in that way you overwrite your db settings, right?
if this is so, i can do the include at the bottom at the `settings.php` too.

regarding testing `prod` settings in local, i think i can do a special option for that, because i think your case is special and not everybody is in this usecase (having the `dev` db settings in `settings.local.php`)

would do this make you happy? ^^

**Comment by FatherShawn** [comment]
That would take care of my use case, but I'm imagining that there are many use cases where `settings.local.php` is expected to be loaded when running in local development and also where developers would want to run the site in "prod" mode for testing.  That's the core of what I'm trying to say.

**Comment by novia713** [comment]
so a `site:mode prod --local` would do the trick not deleting the following line?
```php
<?php include __DIR__ . "/settings.local.php"; ?>
```

**Comment by novia713** [comment]
@FatherShawn @jmolivas @enzolutions 
just commited the `--local` option for `site:mode prod`
it just keeps the include to `settings.local.php` but comments out the `cache bins` lines in it 😉

**Comment by jmolivas** [comment]
@novia713 Thanks for your contribution, your PR was merged. This will be included on the next release.

**Comment by jmolivas** [comment]
@FatherShawn thanks for your participation on this PR.

**Comment by FatherShawn** [comment]
@jmolivas Thank you for the gift of Drupal Console!  I hope to help out more in the new year - it is an awesome project :)

**Comment by LOBsTerr** [comment]
@jmolivas it can be closed

**Pull request merged**
