### PR TITLE
Generate 'annotation' style plugin

### PR DESCRIPTION
**Pull request by Sutharsan**
This adds a generator for a custom annotation style plugins: `generate:plugin:type:annotation`
The following files and directories is are being generated:
- src/Annotation/ExamplePlugin.php
- src/Plugin/ExamplePlugin/
- src/Plugin/ExamplePluginBase.php
- src/Plugin/ExamplePluginInterface.php
- src/Plugin/ExamplePluginManager.php
- module.services.yml

### CODE REVIEW

**Comment by Sutharsan** [comment]
This pull request is simpler than the one in pull request https://github.com/hechoendrupal/DrupalConsole/pull/499 and has less input options. But both add a custom plugin type with annotation discovery.

**Comment by jmolivas** [comment]
@Sutharsan: Thanks for the PR, I will be testing it later on today.

**Comment by jmolivas** [comment]
This looks great @Sutharsan. I run `phpcs` and this is the result of testing the drupal coding standards
```
FILE: ...pal8.dev/modules/custom/example/src/Plugin/ExamplePluginBase.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 17 | WARNING | [x] There must be no blank line following an inline
    |         |     comment
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

FILE: ...dev/modules/custom/example/src/Plugin/ExamplePluginInterface.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 17 | WARNING | [x] There must be no blank line following an inline
    |         |     comment
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

FILE: ...8.dev/modules/custom/example/src/Plugin/ExamplePluginManager.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 15 | ERROR | [x] Doc comment short description must start with a
    |       |     capital letter
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 56ms; Memory: 4.75Mb
```

The error is generated from line 19 at  `templates/module/src/plugin-type-annotation-manager.php.twig`

A solution could be update current code 
```
/**
 * {{ label }} plugin manager.
 */
```
With:
```
/**
 * Provides the {{ label }} plugin manager.
 */
```

**Comment by Sutharsan** [comment]
Done.

**Pull request merged**
