### PR TITLE
[site:import:local] New command for "importing" existing sites.

### PR DESCRIPTION
**Pull request by esolitos**
Currently it's very easy start using drupal console from scratch, however there's no automated way to start working on existing projects.
With this new command i want to allow users to simply add their existing local sites to the console configuration with a simple command.

Let me know what you think about this, i'm fully open to suggestions.

### CODE REVIEW

**Comment by jmolivas** [comment]
@esolitos Thanks for your contribution! We'll take a look at it as soon as possible!

**Comment by jmolivas** [comment]
I totally love this feature :+1:

**Comment by esolitos** [comment]
HeHe Nice to hear.

**Comment by jmolivas** [comment]
@esolitos I did make some improvements and this PR https://github.com/hechoendrupal/DrupalConsole/pull/2134

Sorry for have them fixed myself instead of asking you to do, but we are planning a release this week and I really wanted to include this PR.

**Comment by jmolivas** [comment]
@esolitos  PR was merged. This will be included on next release, Thanks.

**Comment by esolitos** [comment]
Great!
I've looked at your changes, I'll keep them in mind for the next contributions!

**Pull request merged**
