### PR TITLE
Add a simple generate:form command

### PR DESCRIPTION
**Pull request by alxvallejo**
One note is that I'm passing $this->formType to FormGenerator->generate() and passing the argument in the middle. I'm passing this to determine the template and whether to update/ask for routing.

I'm also using the existing filename form.php.twig for this new bare form template and copying the existing template to form-config.php.twig.

### CODE REVIEW

**Comment by jmolivas** [comment]
@alxvallejo: Thanks for  the PR, I will take a look.

**Comment by omero** [comment]
@alxvallejo the code generated by `generate:form:config` command using the `form-config.php.twig` template in this PR does not meet the coding standards of Drupal thats the reason why travis fails.

The template indents the code erroneously, i recommend you use the coder snifer project https://www.drupal.org/node/1419988 to the generated code, and fix the twig template to make it work :smile:

**Comment by jmolivas** [comment]
@alxvallejo: Thanks for the PR, I will review and merge.

**Comment by jmolivas** [comment]
@alxvallejo The PR has conflicts. Are you interested on fixing them ?

**Comment by alxvallejo** [comment]
Thanks Jesus, I'll take a look

**Comment by jmolivas** [comment]
Feel free to ask here or ping us at the gitter chat.

**Comment by jmolivas** [comment]
@alxvallejo: Thanks for the PR.

**Comment by StryKaizer** [comment]
Oh, was looking for this. Great work!  Thanks!!!

**Pull request merged**
