### PR TITLE
Rename EntityListController to EntityListBuilder.

### PR DESCRIPTION
**Pull request by pfrenssen**
In [Issue #2120871: Rename EntityListController to EntityListBuilder](https://www.drupal.org/node/2120871) the classes that generate the entity listings have been renamed and moved into the root namespace of the modules. We should do the same in our generated code.

### CODE REVIEW

**Comment by pfrenssen** [comment]
This still needs to be tested.

**Comment by jmolivas** [comment]
@pfrenssen: thanks for the PR, seems good to me, I will do some test of the code generation and reply with more comments.

**Comment by jmolivas** [comment]
Found two bugs and creted one issue https://github.com/hechoendrupal/DrupalConsole/issues/808 the other was already reported on this issue https://github.com/hechoendrupal/DrupalConsole/issues/807

**Comment by jmolivas** [comment]
I will merged this on and send a PR fixing the reported issues.

**Pull request merged**
