### PR TITLE
[module:search] modulename --composer working [#2351]

### PR DESCRIPTION
**Pull request by novia713**
#2351

seleccion_658

### CODE REVIEW

**Comment by darol100** [comment]
Great work, but I think this will make confusing between debug and search. This command will provide information about each module no matter what if enable or disable (very similar to debug).

I propose to split the functionality of `module:debug` into `--enable`, which is going to only show enable modules, and this will be the default. And `--disable`, which will only show disable modules.

Then we could move this functionality another argument called `--composer`, which will provide this information. 

The end result if te user wants to show module enable or disable they could do something like   `module:debug —enable —disable —composer`. 

What you guys think ? @novia713 , @jmolivas

**Comment by jmolivas** [comment]
@novia713 I like your idea about calling `package:search` and we can start using the `package` namespace for composer related commands.

**Comment by novia713** [comment]
i opened a discussion thread about Composer topic in #2353

**Comment by novia713** [comment]
this no longer makes sense :-/

**Pull request closed without merging**
