### PR TITLE
Support Drupal 8.1.x.

### PR DESCRIPTION
**Pull request by pfrenssen**
I like using the [drupal-project](https://github.com/drupal-composer/drupal-project) project for my Drupal projects. This conveniently includes both Drupal core and DrupalConsole.

I just updated the Drupal core version in my project to 8.1.0-beta1 and Composer complained that the Symfony dependencies now are incompatible. Drupal 8.1 is using Symfony 2.8, while Drupal 8.0 uses Symfony 2.7.

We can trivially update our dependencies to be compatible with Drupal 8.1.x and beyond.

### CODE REVIEW

**Comment by jmolivas** [comment]
@pfrenssen  :+1: on this one

**Comment by bojanz** [comment]
+1

**Comment by jmolivas** [comment]
I can merge this and tag a new release 0.10.13 and build `phar` with support for `8.0` and the tag a new release and build a new `phar` once 8.1 get released.

**Comment by jmolivas** [comment]
@pfrenssen @bojanz Merged on this PR https://github.com/hechoendrupal/DrupalConsole/pull/2034

**Comment by pfrenssen** [comment]
Thanks!

**Comment by jmolivas** [comment]
New release tagged v0.10.13 => https://github.com/hechoendrupal/DrupalConsole/releases/tag/0.10.13

**Pull request merged**
