### PR TITLE
router:debug should dump route requirements

### PR DESCRIPTION
**Pull request by webflo**
Requirements are a important part of the route definition. They contain the required permissions to access the route for example (see see system.routing.yml)

### CODE REVIEW

**Comment by webflo** [comment]
Should i open a PR against console-en for the new string?

**Comment by jmolivas** [comment]
@webflo Thanks for the PR and yes please add new string on the language repo

**Comment by webflo** [comment]
PR for the new string. https://github.com/hechoendrupal/drupal-console-en/pull/42

**Comment by jmolivas** [comment]
@webflo Thanks for your contribution, your PR was merged. This will be included on the next release.

**Pull request merged**
