### PR TITLE
#2389 Feature Request: Devel dumper change command 

### PR DESCRIPTION
**Pull request by twhiston**

### CODE REVIEW

**Comment by jmolivas** [comment]
@twhiston Since the command is within DC core namespace `Drupal\px_debug_tools\Command;` must be `Drupal\Console\Command;`

**Comment by twhiston** [comment]
you are completely correct! This is legacy from developing it in a custom module and then moving it into the drupal console command, please accept both my apologies and the updated version of the code ;)

**Comment by twhiston** [comment]
can this now be accepted and merged?

**Comment by jmolivas** [comment]
@twhiston may you sync this PR with the latest changes on master to fix the error `PHP Fatal error:  Trait 'Drupal\Console\Command\ModuleTrait' not found in`

**Comment by twhiston** [comment]
done

**Comment by jmolivas** [comment]
@twhiston PR was merged. This will be included on next release, Thanks.

**Pull request merged**
