### PR TITLE
[translation] Additional Japanese interface translations.

### PR DESCRIPTION
**Pull request by gh640**
Can this PR be merged automatically? If not, I'll fix the problem.

### CODE REVIEW

**Comment by jmolivas** [comment]
@gh640 Please fix merge conflicts.

**Comment by gh640** [comment]
@jmolivas thank you for your reply. I'll retry after fixing the conflicts.

**Comment by gh640** [comment]
I've fixed the merge conflicts and this PR should work.

**Comment by enzolutions** [comment]
Thanks @blauerberg

**Pull request merged**
