### PR TITLE
New command Site:New

### PR DESCRIPTION
**Pull request by enzolutions**

### CODE REVIEW

**Comment by jmolivas** [comment]
As specified at System requirements page 
- Drupal 8: PHP 5.5 or higher  
https://www.drupal.org/requirements

**Comment by derhasi** [comment]
As mentioned by @webflo  in #685, this change makes it impossible to use drupal console and Drupal core in a single project (having the same composer.json), due to using guzzle 6. Drupal Core uses Guzzle 5 at the moment. @enzolutions can the same functionality be provided with Guzzle 5, as long as Core uses that?

**Comment by enzolutions** [comment]
@derhasi 

Do you mean change DrupalConsole composner.json from **guzzlehttp/guzzle": "~6.0.1",** to **guzzlehttp/guzzle": "~5.0.0"** ?

**Comment by webflo** [comment]
@enzolutions yes

**Comment by jmolivas** [comment]
Them idea is t

**Comment by jmolivas** [comment]
@derhasi , @webflo I sent and merged a PR https://github.com/hechoendrupal/DrupalConsole/pull/754 with this fix

**Pull request merged**
