### PR TITLE
user:create command (resolves #2743)

### LINKED ISSUE #2743: [create:users] or [user:new] with a name
At the moment is impossible to create a user with a fixed name, you can generate a lot (or few) with random name/roles but you can create one with a fixed username. I don't know if the proper place is create:users or we should move it to user:new or generate:user

### PR DESCRIPTION
**Pull request by daydiff**

### CODE REVIEW

**Comment by enzolutions** [comment]
@daydiff thanks for your contribution. I tested and works perfectly.

Could you create a PR to include English string for your command at repo https://github.com/hechoendrupal/drupal-console-en to accept this PR

**Comment by daydiff** [comment]
@enzolutions I'v created it https://github.com/hechoendrupal/drupal-console-en/pull/23

**Comment by enzolutions** [comment]
Awesome @daydiff

**Comment by jmolivas** [comment]
@daydiff Thanks for your contribution, your PR was merged. This will be included on the next release.

**Pull request merged**
