### PR TITLE
[multisite:new] Sets up files for a new multisite installation #23

### PR DESCRIPTION
**Pull request by jludwig**
Addresses issue ##2253

```
Usage:
  multisite:new [options] [--] [<sites-subdir>]

Arguments:
  sites-subdir               Name of directory under 'sites' which should be created.

Options:
      --site-uri[=SITE-URI]  Site URI to add to sites.php
      --copy-install         Copies existing site from the default install.
  
Help:
 The multisite:new command assists in setting up new multisite installs by creating the needed subdirectory and files, and can optionally copy an existing 'default' installation

```

So, if someone wants to just create a directory with a settings.php file they could do:

`$ drupal multisite:new files_only`

If they wanted to instead copy what was already installed on default and add it to sites.php they could do:

`$ drupal multisite:new --site-uri copy-install.localhost --copy-install copy_install`

multisite-new

@TODO:

- Address #2333

### CODE REVIEW

**Comment by jmolivas** [comment]
@jludwig Do you like to address #2333 on the same PR or work on another PR instead?

**Comment by jludwig** [comment]
@jmolivas The latest commit deals with #2333 so in this PR is fine.

The commit before it adds some more exception handling, but I'm rushing out the door right now so it doesn't have as much cleanup and testing as I'd usually like. D:

Still, it's handling issues better now.

**Comment by darol100** [comment]
@jmolivas This command should be register as service ? https://github.com/hechoendrupal/DrupalConsole/issues/2225  If so, shall we take care of this before merging ?

**Comment by jmolivas** [comment]
I think is fine to merge like is it and then we can apply the changes to register as a service

**Comment by jmolivas** [comment]
@darol100 did you test it?

**Comment by darol100** [comment]
No...

**Comment by jludwig** [comment]
Uh, I don't get why that last check failed. It still works on my end since Command uses HelpTrait anyway. :/

**Comment by jmolivas** [comment]
@jludwig can you sync your branch with master, since lots of changes merged latelly and update the PR

**Comment by jludwig** [comment]
@jmolivas @darol100 I made the changes to register it as a service.

**Comment by jmolivas** [comment]
@jludwig Tested this and work as expected.

drupal-multisite-new

**Comment by jmolivas** [comment]
@jludwig PR was merged. This will be included on next release, Thanks.

**Pull request merged**
